### PR TITLE
Fixing syntax error in schedule

### LINKED ISSUE #2: /scrape_schedule/{date} is not picking up round on second day
**Describe the bug**
If you scrape the schedule for the second day of a round, the round is set to 0. 

**To Reproduce**
1. GET {{url}}/scrape_schedule/20190324
2. Check the db

**Expected behavior**
Round set to 2 for scraped games

### PR DESCRIPTION
**Pull request by ALeonard9**
Fixes #2

### CODE REVIEW

File: backend/lib/scraper.js [hunk 1]
```diff
@@ -383,13 +383,13 @@ function scrape_schedule(date_var){
                 case date_var < 20190323:
                   round = '1';
                   break;
-                case date_var >= 20190323 && date_var < 20190324:
+                case date_var >= 20190323 && date_var <= 20190324:
```
Comment (AlexCromer) [inline backend/lib/scraper.js:386]: I would suggest running all these date checks against a newly instantiated date, if possible. Similar to `var today = new Date();` But until we're able to pull the rounds dynamically from sites or something this can work!

**Comment by AlexCromer** [comment]
I would suggest running all these date checks against a newly instantiated date, if possible. Similar to `var today = new Date();`

File: backend/lib/scraper.js (hunk 1 above)
Comment (ALeonard9) [reply backend/lib/scraper.js:386]: Added to Project backlog.

Comment (ALeonard9) [reply backend/lib/scraper.js:386]: 🎈
